[package]
name = "prometheus-mdns-sd-rs"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdns = { version = "0.3", git = "https://github.com/bkchr/mdns", branch = "tokio_rewrite" }
futures = "0.1.28"
tokio = "0.1.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
maplit = "1.0"